server:
  port: 9005

spring:
  application:
    name: log-service    # eureka 서버에 등록된 Application 이름으로 사용됨
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8b303.p.ssafy.io:3306/alcol?serverTimezone=Asia/Seoul
    username: root
    password: ehgud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  redis:
    host: i8b303.p.ssafy.io
    port: 6000
    password: ehgud

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://i8b303.p.ssafy.io:8761/eureka   # 이 위치에 user-service 를 등록하겠다.
