server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:

        # login
        - id: user-service
          uri: http://localhost:9000/   # final request -> http://127.0.0.1:9000/login
          predicates:
            - Path=/user-service/login # http://{gateway-ip:gateway-port}/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}  # remove '/user-service'

        # logout
        - id: user-service
          uri: http://localhost:9000/   # final request -> http://127.0.0.1:9000/logout
          predicates:
            - Path=/user-service/logout # http://{gateway-ip:gateway-port}/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}  # remove '/user-service'

        # signUp
        - id: user-service
          uri: http://localhost:9000/   # final request -> http://127.0.0.1:9000/user-service/
          predicates:
            - Path=/user-service/
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        # refresh
        - id: user-service
          uri: http://localhost:9000/   # final request -> http://127.0.0.1:9000/user-service/refresh
          predicates:
            - Path=/user-service/refresh
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RefreshTokenFilter

        # other user-service requests
        - id: user-service
          uri: http://localhost:9000/   # final request -> http://127.0.0.1:9000/user-service/**
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AccessTokenFilter


access-token:
  expiration_time: 60000 # milliseconds
  secret: qweasdzcxqweasdzxcqweasdzxcqweasdzxcasdqweasdzcxasdqweasdaczxdasdqwcxcasdqwdcxcasdqwescxczdsqewscsacsadsadw

refresh-token:
  expiration_time: 1200000 # milliseconds
  secret: poipoipoipoipoipoipoipoiqweqweqweqwepoipoipoiqweqwepoiqwpeoiqpwoeipqowiepqoiwepoiqwpeiqpweipqwieoqweiqwpeiowi
