server:
  port: 9000

spring:
  application:
    name: user-service    # eureka 서버에 등록된 Application 이름으로 사용됨
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8b303.p.ssafy.io:3306/alcol?serverTimezone=Asia/Seoul
    username: root
    password: ehgud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka   # 이 위치에 user-service 를 등록하겠다.

access-token:
  expiration_time: 30000 # milliseconds
  secret: qweasdzcxqweasdzxcqweasdzxcqweasdzxcasdqweasdzcxasdqweasdaczxdasdqwcxcasdqwdcxcasdqwescxczdsqewscsacsadsadw

refresh-token:
  expiration_time: 1200000 # milliseconds
  secret: poipoipoipoipoipoipoipoiqweqweqweqwepoipoipoiqweqwepoiqwpeoiqpwoeipqowiepqoiwepoiqwpeiqpweipqwieoqweiqwpeiowi
