server:
  port: 9000

spring:
  application:
    name: user-service    # eureka 서버에 등록된 Application 이름으로 사용됨
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{ip 주소}/alcol?serverTimezone=Asia/Seoul
    username: root
    password: {redis password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  redis:
    host: {ip 주소}
    port: 6000
    password: {redis password}

logging:
  level:
    com:
      alcol:
        userservice:
          util:
            FileHandler: ERROR

cloud:
  aws:
    s3:
      bucket: kimjusung-bucket
    credentials:
      access-key: {cloud access-key}
      secret-key: {cloud secret-key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://{ip 주소}:8761/eureka   # 이 위치에 user-service 를 등록하겠다.

access-token:
  expiration_time: 1000000 # milliseconds
  secret: {access-token secret-key}

refresh-token:
  expiration_time: 3000000 # milliseconds
  secret: {refresh-token secret-key}
